---
title: "케임브리지 한인교회 투어 (2019) - 눈을 떠요"
#description: |
  
author:
  - name: Hyesop Shin 
    url: https://hyesop.rbind.io
    affiliation: Dept.of Geography, University of Cambridge
    affiliation_url: https://www.geog.cam.ac.uk/
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Cambridge Tour

안녕하세요 여러분! 케임브리지 투어에 참석해주셔서 진심으로 감사드립니다.
개인적으로 학생 신분으로 마지막 관광안내가 될 것 같아서 이렇게 블로그 형태로 작성하였으니 나중에 다시 보고 싶으실 때 참고해주세요!

금일 관광일정은 다음과 같습니다.

* 관광 소요시각: 2-3시간
* 관광 장소: 코퍼스 시계, 이글 펍, 렌 도서관, 곤빌 앤 키즈, 트리니티, 세인트 존스


### What to look at?
* 컬리지 설립자가 누구인가: 성직자, 왕족, 시민, 의사
* 건축물 양식이 어떤가: 고딕, 로마네스크, 긴 창문과 벽돌
* 계급의 상징: Court와 Grass
* 계급: 노블맨, 펜셔너, 사이저



## 참고서적

* 옥스포드와 케임브리지
* 위키피디아 
* 나무위키
* 그외 블로그 컬리지 홈페이지


## 지도

지도는 다음과 같습니다.


<!--지도 필요-->



## 들어가며

* Q. 케임브리지에 대해서 알려주세요.

케임브리지는 Cam강과 Bridge의 합성어입니다. 너무 간단하죠?
또한 영국 내에서 다리이름이 붙어있는 유일한 주랍니다.
그 다리는 어디있나하면 모들린 컬리지(Magdalene College)근처에 있는 다리랍니다.


* Q. 케임브리지랑 옥스포드는 컬리지 시스템이라는게 있다던데요, 그게 무슨 말인가요?

당장 입학 지원서를 작성할 때에도 컬리지를 대뜸 선택하라고 합니다. 대략난감한 상황이 시작된 것이죠.
한국사람 입장에서는 대학 - 단과대학 - 학과의 위계가 수직적으로 이해되실 거에요.
그러나 옥스브리지에서의 컬리지는 조금 개념정의가 달라요.

여기에서 말하는 컬리지 시스템(Collegiate System)이란, 대학의 기능이 대학본부와 대학소속의 컬리지로 구분된 것을 의미합니다. <br>
* 교육과 연구의 기능: 대학본부, 연구기관, 도서관, 학과에서 담당
* 복지, 행정, 심화학습의 기능: 학생 (학석박 과정 모두 해당), 연구원 및 교수 (일부해당)의 숙소, 각종 행정처리, 장학 등 담당

따라서 케임브리지의 경우, 대학본부와 31개의 컬리지로 이루어져 있으며 이 32개 기관이 각자의 독립된 행정과 복지를 담당하게 됩니다.

이 전통은 대학설립 때 수도사들의 신앙과 지식의 향상과 엄격한 생활규율을 유지하기 위한 수단으로 만들었고요, 오늘날에도 비슷한 기능을 담당하고 있습니다.

**그게 나랑 무슨 상관이냐고요?**. 
학부생의 경우, 컬리지 단위로 모집학과 학생이 정해져 있어 학생의 선택에 따라서 자주 만나는 친구들 무리가 달라질 수 있고요, 
컬리지의 재정상황에 따라서 복지혜택도 그만큼 달라지기 때문에 장학혜택 또한 달라질 수 있답니다. 물론 빵빵한 컬리지의 경쟁률은 엄청나게 치열하죠.
한국에서는 학과에서 학번별로 담당지도교수가 있어요, 주로 졸업과 진로 이야기를 위한.
케임브리지 컬리지에서는 학부생을 위해서는 Director of Studies (DOS), 대학원생을 위해서는 Graduate Tutor 제도를 두고 있어요.
학생의 학업성취도를 진단하고 평가하기 위한 건데요, 
학생이 공부를 못따라가면 사람을 연결해서 도움을 줄 수가 있고요,
종교적 정신적으로 어려움이 있는 경우에는 친절한 상담을 통해 학업에 이상이 없도록 도와줍니다.
장애학생의 경우에는 강의실까지 이동편의를 위해 택시 서비스를 제공하기도 하며, 
연말시험을 학과 시험장이 아니라 컬리지 내 별도의 장소에서 시험을 볼 수 있게 허락해줍니다.
연구얘기는 하나도 없습니다^^.

이 제도가 별것 아닌것 같지만, 경험상 컬리지 제도는 학생에게 득득득!


* Q. 몇개의 컬리지가 있나요?

컬리지 31개 - 한때는 34개
처음 설립된 컬리지들 중에는 Hall이라고 불렸던 것들이 많다
의미는 원래 홀에서 생활하는 학생과 펠로들을 지칭하는 말이었음
처음 '홀'의 명칭을 사용하는 컬리지는 트리니티 홀, 휴즈 홀




## 케임브리지에 대하여

* Q. 케임브리지 대학은 언제 설립되었나요?

케임브리지 대학은 1209년에 설립되었어요. <br>
첫 컬리지 설립은 1284년 Peterhouse를 시작으로 2010년 Homerton이 31번째로 설립되었답니다.
첫 컬리지 설립 전까지는 사람들이 교회 강당에 모여서 강의하고 토론 하였답니다.


그래서 **성자와 학자의 도시** (The city of Saints and Scholars)라고 합니다.

* Q. 어떤 계기로 설립되었나요?

왜 옮겨왔나? 학교태동시점부터 학생vs시민 갈등이 많았음.
1209년에 부녀자를 살해한 사건으로 옥대 교수 및 학생들이 자유롭게 공부할 곳을 찾아 케임브리지로 오게 됨 (1차).
1355년 옥대 학생들이 맥주맛에 불만을 느껴 주인얼굴에 뿌린사건이 발단이 되어 시민vs학생사이에 전쟁이 일어나 사망자 발생(2차).
수습하는 과정에서 재판 및 벌금부과 문제로 당시에 도시와 대학간 감정이 좋지 않았고 옥vs캠 싸움으로 번지게 됨.


* Q. 왜 대학이 케임브리지에 새워졌을까?
옥스포드, 혹은 다른 상업도시도 있었을텐데
여러 의문점이 있지만 한가지 분명한 사실은 이곳에서 교수와 학생공동체가 국왕과 교회로부터 확실한 보호를 약속받았다는 점이다
대학에 대한 시민들의 위협이 심각했다







