---
title: "코로나 바이러스와 시뮬레이션"
description: |
  행위자기반모형이 공중보건정책에 기여할 수 있을까?
author:
  - name: 신혜섭
    url: 
    affiliation: 케임브리지 지리학과
    affiliation_url: https://www.geog.cam.ac.uk/people/shin
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# 머리말

코로나 바이러스 (SAR-COV-2)는 2019년 12월 중국 우한시에서 최초 발생하였으며, 2020년 5월 현재 중국을 넘어 전세계 212개국 30만 명의 목숨을 앗아갔다. 
국내에는 1월 20일 우한에서 입국한 중국여성의 확진판정을 시작으로 확진자가 꾸준히 증가했으며, 2월에는 지역사회 감염이 본격화되면서 하루 최대 천명에 육박할 정도로 폭발적인 증가를 기록한 이후, 현재 소강기에 접어들었다. 
정부는 지난 4개월 동안 코로나 확산방지를 위해 선별진료소 설치, 감염경로 역학조사, 공적 마스크 제공, 사회적 거리두기, 해외입국자 의무 자가격리 등 각고의 노력을 하고 있으며, 민간 차원에서도 코로나 맵과 마스크 알리미 등 국민들의 안전에 크게 기여하였다.


코로나 대유행이 시작되자 전세계 학계와 산업계에서는 전염병모형을 개발하여 코로나 확산 예측 및 저지를 위해 심혈을 기울이고 있다. 
특히 슈퍼전파자의 이동, 자가격리자의 이탈이 집단감염에 단초가 되면서 개인의 이동 행태를 빠르게 추적하는 것이 전염병 조기억제에 중요한 변수로 자리 잡았다. 
이와 같이 개인의 행태적 특성과 공간적 이동을 반영할 수 있는 모형 중에서 행위자기반모형(Agent-based modelling)이 있다. 
이 글에서는 국내 코로나 바이러스의 확산과정을 탐색하고, 사례를 통해 행위자기반모형이 질병 통제에 어떻게 적용될 수 있는지 살펴보고자 한다.


# 코로나19의 확산단계와 경로
2020년 1월 20일 국내에서 최초로 발생했던 코로나19는 한 달여 기간 동안 수도권 및 전국 각 지역에 산발적으로 분포했다 (확산1단계). 
이 기간 동안 확진자들의 경로추적이 가능했다. 확산2단계는 집단감염을 촉매로 확산이 폭발적으로 증가하는 시기로 지역사회 감염이 급증하는 시기였다. 
대구 신천지교회 신도 사이에서 급속도로 확산된 바이러스는 2월부터 3월까지 대구 경북지역을 중심으로 9800명, 당일 확진자 최대 1000명, 그리고 누적사망자는 150여 명을 기록하였다. 
4월 초부터 5월 초 현재까지는 바이러스 확산이 잦아드는 확산3단계로, 일평균 확진자가 30명 이하로 줄어드는 시기이다. 해당기간동안 서울 및 수도권에서 소규모 집단감염이 수차례 발생하였으며, 확진자 대부분은 해외교민이었다.


질병관리본부는 코로나의 주 확산경로를 사람 간의 비말감염 혹은 밀접접촉을 통한 전파 혹은 오염된 표면이나 물체와의 접촉에 의한 전파로 분석하고 있다. 바이러스 감염 시 대개 1-14일 정도의 잠복기 후 기침, 발열, 호흡곤란 등의 증상을 보이지만 간혹 무증상자들도 있다. 국내언론 및 외신에 의하면 연령이 많고 기저질환이 있는 사람일수록 감염에 따른 사망 가능성이 높아진다는 보고가 있었다. 실제 유럽과 미국 양로원에서는 코로나 확진 판정 이후 사망하는 사례가 수십 건이 있었고, 국내에서는 요양병원 내 확진자들 중에서 고위험 환자들이 사망했다. 그럼에도 국내에서는 비교적 마스크 착용, 방역, 확진자 경로공개 등 코로나 확산을 선제적으로 방어한 까닭에 이동제한(Lockdown) 없이도 일상생활을 이어가고 있으나, 코로나 바이러스의 높은 전파력으로 인해 밀접접촉 가능성이 높은 교회, 실내운동시설, 콜센터, 유흥업소 등 실내 다중이용 시설은 여전히 긴장의 끈을 놓지 않고 있다.



